name: translator
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  flutter_svg: ^1.1.6
  flutter_speed_dial: ^6.2.0
  flutter_launcher_icons: ^0.11.0
  change_app_package_name: ^1.1.0
  lottie: ^1.4.3
  share_plus: ^4.4.0
  store_checker: ^1.1.0
  flutter_rating_bar: ^4.0.1
  in_app_review: ^2.0.6
  speech_to_text: ^6.1.1
  avatar_glow: ^2.0.2
  flutter_tts: ^3.6.2
  flutter_spinkit: ^5.1.0
  google_mlkit_text_recognition: ^0.5.0
  image_picker: ^0.8.6
  image_cropper: ^3.0.1
  flutter_swipe_action_cell: ^3.0.6
  camera: ^0.10.1

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "Assets/icon/icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - Assets/images/
    - Assets/svg/
    - Assets/icon/
    - Assets/lottie/
    -
  fonts:
    - family: robor
      fonts:
        - asset: Assets/font/ROBOTO-LIGHT.ttf
    - family: robob
      fonts:
        - asset: Assets/font/ROBOTO-BOLD.ttf

